name: Index Contentful data in Typesense
description: Creates collections and indexes Contentful data into Typesense
author: Autotelic
inputs:
  locale:
    required: true
    default: en-US
  includeDrafts:
    required: true
    default: true
  typesenseAction:
    description: Typesense bulk action
    default: bulkIndexing
  contentfulSpaceId:
    required: true
  contentfulEnvironment:
    required: true
    default: master
  contentTypeMappingsPath:
    required: true
    default: ./contentTypeMappings.json
  contentManagementToken:
    required: true
  typesenseAdminApiKey:
    required: true
  typesenseUrl:
    required: true
    default: http://localhost:8108

runs:
  using: node16
  main: dist/index.js
